"""qr code1

Revision ID: 042149f7cfb9
Revises: dad85ce360ab
Create Date: 2024-07-26 14:36:39.671917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '042149f7cfb9'
down_revision: Union[str, None] = 'dad85ce360ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_images', 'transformed_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_images', 'transformed_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
