"""new database

Revision ID: 32eb08b1b181
Revises: 
Create Date: 2024-07-26 19:45:13.525742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32eb08b1b181'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('transformed_images', 'transformed_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transformed_images', 'qr_code_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformed_images', sa.Column('qr_code_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('transformed_images', 'transformed_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
