"""qr code1

Revision ID: 54032607591c
Revises: 042149f7cfb9
Create Date: 2024-07-26 15:32:34.768246

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54032607591c'
down_revision: Union[str, None] = '042149f7cfb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qr_codes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('photo_id', sa.UUID(), nullable=False),
    sa.Column('qr_code_url', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('transformed_images', 'qr_code_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transformed_images', sa.Column('qr_code_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('qr_codes')
    # ### end Alembic commands ###
