"""add qr_code into Transformed

Revision ID: 56741664db20
Revises: 
Create Date: 2024-07-25 21:41:45.892842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56741664db20'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('photo_tag', 'photo_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('photo_tag', 'tag_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('transformed_images', sa.Column('qr_code_url', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transformed_images', 'qr_code_url')
    op.alter_column('photo_tag', 'tag_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('photo_tag', 'photo_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
