"""update qr_code_url

Revision ID: c066e08d23a7
Revises: 56741664db20
Create Date: 2024-07-25 21:55:04.192778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c066e08d23a7'
down_revision: Union[str, None] = '56741664db20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_images', 'qr_code_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transformed_images', 'qr_code_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
